#!/usr/bin/env bash
# Install the daily vault-health and conflict-scan cron jobs into the
# CURRENT USER's crontab (no sudo needed). Idempotent. Run as dbexpertai
# from the jetsonlocalai repo root:
#
#   bash hermes-agent/vault-crons/install-vault-crons.sh
#
# What it does:
#   1. Creates ~/.local/share/vault-crons/ for log output.
#   2. Adds two cron lines (or replaces the marked block if it already exists):
#      - 04:00 daily: vault-conflict-scan.py
#      - 04:05 daily: vault-health.py
#   3. Verifies the cron lines parse by running each script in --dry-run / --print-only
#      mode before installing.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
SCRIPT_DIR="$REPO_ROOT/hermes-agent/vault-crons"
CONFLICT_SCAN="$SCRIPT_DIR/vault-conflict-scan.py"
HEALTH="$SCRIPT_DIR/vault-health.py"
DIGEST="$SCRIPT_DIR/jetsonlocalai-digest.py"
LOG_DIR="$HOME/.local/share/vault-crons"
MARKER_BEGIN="# >>> jetsonlocalai vault-crons (managed) >>>"
MARKER_END="# <<< jetsonlocalai vault-crons (managed) <<<"

if [ ! -x "$CONFLICT_SCAN" ] || [ ! -x "$HEALTH" ] || [ ! -x "$DIGEST" ]; then
    echo "error: scripts not executable: $CONFLICT_SCAN $HEALTH $DIGEST" >&2
    exit 1
fi

mkdir -p "$LOG_DIR"

echo "=== smoke-test conflict-scan (dry-run) ==="
"$CONFLICT_SCAN" --dry-run

echo "=== smoke-test health (print-only) ==="
"$HEALTH" --print-only >/dev/null
echo "  ok"

echo "=== smoke-test jetsonlocalai-digest (print-only, yesterday) ==="
"$DIGEST" --print-only >/dev/null
echo "  ok"

# Build the new cron block.
BLOCK=$(cat <<EOF
$MARKER_BEGIN
# Generated by hermes-agent/vault-crons/install-vault-crons.sh
# Edit the scripts, not this block — re-run the installer to refresh.
0 4 * * * /usr/bin/python3 $CONFLICT_SCAN >> $LOG_DIR/conflict-scan.cron.log 2>&1
5 4 * * * /usr/bin/python3 $HEALTH >> $LOG_DIR/health.cron.log 2>&1
15 4 * * * /usr/bin/python3 $DIGEST >> $LOG_DIR/jetsonlocalai-digest.cron.log 2>&1
$MARKER_END
EOF
)

# Replace any existing managed block; otherwise append.
existing=$(crontab -l 2>/dev/null || true)
if echo "$existing" | grep -qF "$MARKER_BEGIN"; then
    new=$(echo "$existing" | awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" -v block="$BLOCK" '
        $0 == begin { in_block = 1; print block; next }
        $0 == end { in_block = 0; next }
        !in_block { print }
    ')
else
    new=$(printf "%s\n\n%s\n" "$existing" "$BLOCK")
fi

echo "$new" | crontab -

echo
echo "=== installed vault-crons cron block ==="
crontab -l | sed -n "/$MARKER_BEGIN/,/$MARKER_END/p"
echo
echo "Logs will appear under: $LOG_DIR"
